# Generated by Django 4.0.5 on 2022-06-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingunit',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
