# Generated by Django 4.0.5 on 2022-06-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_shoppingunit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingunit',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
