# Generated by Django 4.0.5 on 2022-06-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_shoppingunit_parentid_pricechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricechange',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
